#!/usr/bin/env ruby
# frozen_string_literal: true

require "optparse"

options = {
  output: nil,
  workspace: Dir.pwd,
  include_dependencies: false,
}

parser = OptionParser.new do |opts|
  opts.banner = "Usage: ruby-lsp-lsif [options]"

  opts.on("--version", "Print ruby-lsp version") do
    $LOAD_PATH.unshift(File.expand_path("../lib", __dir__))
    require "ruby-lsp"
    puts RubyLsp::VERSION
    exit(0)
  end

  opts.on("-o", "--output FILE", "Write LSIF output to FILE (default: stdout)") do |file|
    options[:output] = file
  end

  opts.on("-w", "--workspace DIR", "Workspace directory to index (default: current directory)") do |dir|
    options[:workspace] = File.expand_path(dir)
  end

  opts.on("--include-dependencies", "Include gem dependencies in the index (default: false)") do
    options[:include_dependencies] = true
  end

  opts.on("-h", "--help", "Print this help") do
    puts opts.help
    puts
    puts "Generates LSIF (Language Server Index Format) output for a Ruby project."
    puts "See https://microsoft.github.io/language-server-protocol/specifications/lsif/0.6.0/specification/"
    exit(0)
  end
end

begin
  parser.parse!
rescue OptionParser::InvalidOption => e
  warn(e)
  warn("")
  warn(parser.help)
  exit(1)
end

$LOAD_PATH.unshift(File.expand_path("../lib", __dir__))

require "ruby_lsp/internal"
require "ruby_lsp/lsif"

output = if options[:output]
  File.open(options[:output], "w")
else
  $stdout
end

begin
  generator = RubyLsp::LSIF::Generator.new(
    options[:workspace],
    output,
    nil,
    include_dependencies: options[:include_dependencies],
  )
  generator.generate
ensure
  output.close if options[:output]
end
